name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3.3
  - jupyterlab=3.0.12
  - ipywidgets
  - pip:
    - numpy==1.19.5
    - pandas==1.1.5
    - seaborn==0.11.1
    - pandas-profiling==3.4.0
    - pyarrow==9.0.0
    - protobuf==3.20.1
    - wandb==0.10.31