name: train_val_test_split
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3.3
  - pip:
      - requests==2.24.0
      - numpy==1.21.6
      - pandas==1.1.5
      - scikit-learn==0.24.1
      - protobuf==3.20.1
      - wandb==0.10.31
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
