name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3.3
  - pip:
      - numpy==1.21.6
      - scipy==1.5.3
      - pandas==1.1.5
      - protobuf==3.20.1
      - wandb==0.10.21
      - pytest==6.2.2

