name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3.3
  - pip:
    - pyyaml==5.3.1
    - hydra-core==1.0.6
    - protobuf==3.20.1
    - numpy==1.19.5
    - mlflow==1.30.0
    - wandb==0.10.31